### ISSUE TITLE
small issues with output volume

### ISSUE THREAD

**Issue by jsa1969** [vanbwodonk/es8388arduino#1]
When I set _outputSelect_ to _OUTALL_ calls to _setOutputVolume_ only apply to _OUT1_.
I think this is due to the "else" in line 231 of ES8388.cpp.

Also _getOutputVolume_ only ever delivers the volume of _OUT1_, even when I select only _OUT2_.
Perhaps, when only _OUT2_ is being selected _getOutputVolume_ should return the value of _ES8388_DACCONTROL26_ and not _ES8388_DACCONTROL24_.

**Comment by vanbwodonk** [comment]
Thank you, already fixed.
